version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: just_halaa_server
    env_file: .env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 1
    restart: on-failure
    ports:
      - 3001:3001
